### ISSUE TITLE
IAM policy with */ treated as commend block

### ISSUE THREAD

**Issue by lczerepuk** [SublimeText/Terraform#44] opened 2021-01-13 10:26 UTC
Hi, 

In ST3 when I have a IAM policy with "/*", plugin treated this as comment:

![Zrzut ekranu 2021-01-13 o 11 22 29](https://user-images.githubusercontent.com/13296957/104439909-fb51e800-5591-11eb-8149-17a5cccc0df4.png)

For example, in Visual Studio its workings good:

![Zrzut ekranu 2021-01-13 o 11 25 47](https://user-images.githubusercontent.com/13296957/104439999-17ee2000-5592-11eb-8406-a4486072ad55.png)

Can you fix it ? I love ST3 and Your plugin, but this bug is very annoying. ;(

**Comment by jtcastillo** [comment] 2021-06-04 17:11
I fixed this by doing a manual install of the plugin via cloning the repo (see instructions on readme) and commenting out lines 170-178 of Terraform.sublime-syntax. Not submitting a PR because this is a quick hack to fix it enough to suit my needs. I have many IAM s3 policies and I don't use block comments, but others might.

**Comment by hermitmaster** [comment] 2021-06-06 19:05
I’d be happy to take this on if someone could give me some guidance. I’m sure the Java syntax handles this problem, I just don’t know where to look.

**Comment by ryanpcmcquen** [comment] 2021-06-07 20:16
I'm also seeing broken syntax inside of `jsonencode()` with the variable expansion syntax (`"${}"`).

**Comment by hermitmaster** [comment] 2021-06-16 00:36
I found a workaround for this. Remove the quotes from all of the keys and use = instead of :

**Comment by FichteFoll** [comment] 2024-08-01 18:16
I'm closing this as a duplicate of #54, since both are because the JSON syntax with colons as separators is currently not supported.

**Closed by FichteFoll** 2024-08-01 18:16 UTC
